version: '3'
services:
  tradr-db:
    image: postgres:12.4
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: zane
      POSTGRES_PASSWORD: tradrpassword
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~